// Copyright BSOD-Games, All Rights Reserved.
// Authors: Yehor Pohuliaka (zombiHello)

#ifndef BUTTONCODE_H
#define BUTTONCODE_H

namespace le
{
	enum EButtonCode
	{
		BC_None = 0,

		// Keyboard
		BC_KeyFirst = 0,
		BC_KeyNone = BC_KeyFirst,

		BC_Key0,
		BC_Key1,
		BC_Key2,
		BC_Key3,
		BC_Key4,
		BC_Key5,
		BC_Key6,
		BC_Key7,
		BC_Key8,
		BC_Key9,
		BC_KeyA,
		BC_KeyB,
		BC_KeyC,
		BC_KeyD,
		BC_KeyE,
		BC_KeyF,
		BC_KeyG,
		BC_KeyH,
		BC_KeyI,
		BC_KeyJ,
		BC_KeyK,
		BC_KeyL,
		BC_KeyM,
		BC_KeyN,
		BC_KeyO,
		BC_KeyP,
		BC_KeyQ,
		BC_KeyR,
		BC_KeyS,
		BC_KeyT,
		BC_KeyU,
		BC_KeyV,
		BC_KeyW,
		BC_KeyX,
		BC_KeyY,
		BC_KeyZ,
		BC_KeyPad0,
		BC_KeyPad1,
		BC_KeyPad2,
		BC_KeyPad3,
		BC_KeyPad4,
		BC_KeyPad5,
		BC_KeyPad6,
		BC_KeyPad7,
		BC_KeyPad8,
		BC_KeyPad9,
		BC_KeyPadDivide,
		BC_KeyPadMultiply,
		BC_KeyPadMinus,
		BC_KeyPadPlus,
		BC_KeyPadEnter,
		BC_KeyPadDecimal,
		BC_KeyLBracket,
		BC_KeyRBracket,
		BC_KeySemicolon,
		BC_KeyApostrophe,
		BC_KeyBackQuote,
		BC_KeyComma,
		BC_KeyPeriod,
		BC_KeySlash,
		BC_KeyBackslash,
		BC_KeyMinus,
		BC_KeyEqual,
		BC_KeyEnter,
		BC_KeySpace,
		BC_KeyBackspace,
		BC_KeyTab,
		BC_KeyCapsLock,
		BC_KeyNumLock,
		BC_KeyEscape,
		BC_KeyScrollLock,
		BC_KeyInsert,
		BC_KeyDelete,
		BC_KeyHome,
		BC_KeyEnd,
		BC_KeyPageUp,
		BC_KeyPageDown,
		BC_KeyBreak,
		BC_KeyLShift,
		BC_KeyRShift,
		BC_KeyLAlt,
		BC_KeyRAlt,
		BC_KeyLControl,
		BC_KeyRControl,
		BC_KeyLWin,
		BC_KeyRWin,
		BC_KeyApp,
		BC_KeyUp,
		BC_KeyLeft,
		BC_KeyDown,
		BC_KeyRight,
		BC_KeyF1,
		BC_KeyF2,
		BC_KeyF3,
		BC_KeyF4,
		BC_KeyF5,
		BC_KeyF6,
		BC_KeyF7,
		BC_KeyF8,
		BC_KeyF9,
		BC_KeyF10,
		BC_KeyF11,
		BC_KeyF12,

		BC_KeyLast = BC_KeyF12,
		BC_KeyCount = BC_KeyLast - BC_KeyFirst + 1,

		// Mouse
		BC_MouseFirst = BC_KeyLast + 1,

		BC_Mouse1 = BC_MouseFirst,
		BC_Mouse2,
		BC_Mouse3,
		BC_Mouse4,
		BC_Mouse5,
		BC_Mouse6,
		BC_Mouse7,
		BC_Mouse8,
		BC_MouseWheelUp,
		BC_MouseWheelDown,

		BC_MouseLeft = BC_Mouse1,
		BC_MouseRight = BC_Mouse2,
		BC_MouseMiddle = BC_Mouse3,
		BC_MouseLast = BC_MouseWheelDown,
		BC_MouseCount = BC_MouseLast - BC_MouseFirst + 1,

		BC_Last = BC_MouseLast,
		BC_Count = BC_Last - BC_KeyFirst + 1,
	};
}

#endif // !BUTTONCODE_H
